uitest:
    path:     /uitest
    defaults: { _controller: UnitBundle:Default:uiTest }
chain:
    path:     /chain
    defaults: { _controller: UnitBundle:Default:chain }
single:
    path:     /single/{name}
    defaults: { _controller: UnitBundle:Default:single }
run:
    path:     /run/{name}
    defaults: { _controller: UnitBundle:Default:run }
